# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cloud_replay_pb2 as cloud__replay__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cloud_replay_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReplayStub(object):
    """Experimental (not currently available)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListReplays = channel.unary_unary(
                '/replay.Replay/ListReplays',
                request_serializer=cloud__replay__pb2.ListReplaysRequest.SerializeToString,
                response_deserializer=cloud__replay__pb2.ListReplaysResponse.FromString,
                _registered_method=True)
        self.LoadReplay = channel.unary_unary(
                '/replay.Replay/LoadReplay',
                request_serializer=cloud__replay__pb2.LoadReplayRequest.SerializeToString,
                response_deserializer=cloud__replay__pb2.LoadReplayResponse.FromString,
                _registered_method=True)
        self.SeekForRoom = channel.unary_unary(
                '/replay.Replay/SeekForRoom',
                request_serializer=cloud__replay__pb2.RoomSeekRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CloseReplay = channel.unary_unary(
                '/replay.Replay/CloseReplay',
                request_serializer=cloud__replay__pb2.CloseReplayRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteReplay = channel.unary_unary(
                '/replay.Replay/DeleteReplay',
                request_serializer=cloud__replay__pb2.DeleteReplayRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ReplayServicer(object):
    """Experimental (not currently available)
    """

    def ListReplays(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadReplay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SeekForRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseReplay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteReplay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListReplays': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReplays,
                    request_deserializer=cloud__replay__pb2.ListReplaysRequest.FromString,
                    response_serializer=cloud__replay__pb2.ListReplaysResponse.SerializeToString,
            ),
            'LoadReplay': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadReplay,
                    request_deserializer=cloud__replay__pb2.LoadReplayRequest.FromString,
                    response_serializer=cloud__replay__pb2.LoadReplayResponse.SerializeToString,
            ),
            'SeekForRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.SeekForRoom,
                    request_deserializer=cloud__replay__pb2.RoomSeekRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CloseReplay': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseReplay,
                    request_deserializer=cloud__replay__pb2.CloseReplayRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteReplay': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteReplay,
                    request_deserializer=cloud__replay__pb2.DeleteReplayRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'replay.Replay', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('replay.Replay', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Replay(object):
    """Experimental (not currently available)
    """

    @staticmethod
    def ListReplays(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replay.Replay/ListReplays',
            cloud__replay__pb2.ListReplaysRequest.SerializeToString,
            cloud__replay__pb2.ListReplaysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadReplay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replay.Replay/LoadReplay',
            cloud__replay__pb2.LoadReplayRequest.SerializeToString,
            cloud__replay__pb2.LoadReplayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SeekForRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replay.Replay/SeekForRoom',
            cloud__replay__pb2.RoomSeekRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseReplay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replay.Replay/CloseReplay',
            cloud__replay__pb2.CloseReplayRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteReplay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replay.Replay/DeleteReplay',
            cloud__replay__pb2.DeleteReplayRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
