# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import livekit_agent_dispatch_pb2 as livekit__agent__dispatch__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in livekit_agent_dispatch_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentDispatchServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDispatch = channel.unary_unary(
                '/livekit.AgentDispatchService/CreateDispatch',
                request_serializer=livekit__agent__dispatch__pb2.CreateAgentDispatchRequest.SerializeToString,
                response_deserializer=livekit__agent__dispatch__pb2.AgentDispatch.FromString,
                _registered_method=True)
        self.DeleteDispatch = channel.unary_unary(
                '/livekit.AgentDispatchService/DeleteDispatch',
                request_serializer=livekit__agent__dispatch__pb2.DeleteAgentDispatchRequest.SerializeToString,
                response_deserializer=livekit__agent__dispatch__pb2.AgentDispatch.FromString,
                _registered_method=True)
        self.ListDispatch = channel.unary_unary(
                '/livekit.AgentDispatchService/ListDispatch',
                request_serializer=livekit__agent__dispatch__pb2.ListAgentDispatchRequest.SerializeToString,
                response_deserializer=livekit__agent__dispatch__pb2.ListAgentDispatchResponse.FromString,
                _registered_method=True)


class AgentDispatchServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateDispatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDispatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDispatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentDispatchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDispatch': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDispatch,
                    request_deserializer=livekit__agent__dispatch__pb2.CreateAgentDispatchRequest.FromString,
                    response_serializer=livekit__agent__dispatch__pb2.AgentDispatch.SerializeToString,
            ),
            'DeleteDispatch': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDispatch,
                    request_deserializer=livekit__agent__dispatch__pb2.DeleteAgentDispatchRequest.FromString,
                    response_serializer=livekit__agent__dispatch__pb2.AgentDispatch.SerializeToString,
            ),
            'ListDispatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDispatch,
                    request_deserializer=livekit__agent__dispatch__pb2.ListAgentDispatchRequest.FromString,
                    response_serializer=livekit__agent__dispatch__pb2.ListAgentDispatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'livekit.AgentDispatchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('livekit.AgentDispatchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentDispatchService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateDispatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/livekit.AgentDispatchService/CreateDispatch',
            livekit__agent__dispatch__pb2.CreateAgentDispatchRequest.SerializeToString,
            livekit__agent__dispatch__pb2.AgentDispatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDispatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/livekit.AgentDispatchService/DeleteDispatch',
            livekit__agent__dispatch__pb2.DeleteAgentDispatchRequest.SerializeToString,
            livekit__agent__dispatch__pb2.AgentDispatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDispatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/livekit.AgentDispatchService/ListDispatch',
            livekit__agent__dispatch__pb2.ListAgentDispatchRequest.SerializeToString,
            livekit__agent__dispatch__pb2.ListAgentDispatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
