# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cloud_replay.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63loud_replay.proto\x12\x06replay\x1a\x1bgoogle/protobuf/empty.proto\"\x14\n\x12ListReplaysRequest\":\n\x13ListReplaysResponse\x12#\n\x07replays\x18\x01 \x03(\x0b\x32\x12.replay.ReplayInfo\"\x1f\n\nReplayInfo\x12\x11\n\treplay_id\x18\x01 \x01(\t\"O\n\x11LoadReplayRequest\x12\x11\n\treplay_id\x18\x01 \x01(\t\x12\x11\n\troom_name\x18\x02 \x01(\t\x12\x14\n\x0cstarting_pts\x18\x03 \x01(\x03\")\n\x12LoadReplayResponse\x12\x13\n\x0bplayback_id\x18\x01 \x01(\t\"3\n\x0fRoomSeekRequest\x12\x13\n\x0bplayback_id\x18\x01 \x01(\t\x12\x0b\n\x03pts\x18\x02 \x01(\x03\")\n\x12\x43loseReplayRequest\x12\x13\n\x0bplayback_id\x18\x01 \x01(\t\"(\n\x13\x44\x65leteReplayRequest\x12\x11\n\treplay_id\x18\x01 \x01(\t2\xdd\x02\n\x06Replay\x12\x46\n\x0bListReplays\x12\x1a.replay.ListReplaysRequest\x1a\x1b.replay.ListReplaysResponse\x12\x43\n\nLoadReplay\x12\x19.replay.LoadReplayRequest\x1a\x1a.replay.LoadReplayResponse\x12>\n\x0bSeekForRoom\x12\x17.replay.RoomSeekRequest\x1a\x16.google.protobuf.Empty\x12\x41\n\x0b\x43loseReplay\x12\x1a.replay.CloseReplayRequest\x1a\x16.google.protobuf.Empty\x12\x43\n\x0c\x44\x65leteReplay\x12\x1b.replay.DeleteReplayRequest\x1a\x16.google.protobuf.EmptyBEZ\"github.com/livekit/protocol/replay\xaa\x02\rLiveKit.Proto\xea\x02\x0eLiveKit::Protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud_replay_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\"github.com/livekit/protocol/replay\252\002\rLiveKit.Proto\352\002\016LiveKit::Proto'
  _globals['_LISTREPLAYSREQUEST']._serialized_start=59
  _globals['_LISTREPLAYSREQUEST']._serialized_end=79
  _globals['_LISTREPLAYSRESPONSE']._serialized_start=81
  _globals['_LISTREPLAYSRESPONSE']._serialized_end=139
  _globals['_REPLAYINFO']._serialized_start=141
  _globals['_REPLAYINFO']._serialized_end=172
  _globals['_LOADREPLAYREQUEST']._serialized_start=174
  _globals['_LOADREPLAYREQUEST']._serialized_end=253
  _globals['_LOADREPLAYRESPONSE']._serialized_start=255
  _globals['_LOADREPLAYRESPONSE']._serialized_end=296
  _globals['_ROOMSEEKREQUEST']._serialized_start=298
  _globals['_ROOMSEEKREQUEST']._serialized_end=349
  _globals['_CLOSEREPLAYREQUEST']._serialized_start=351
  _globals['_CLOSEREPLAYREQUEST']._serialized_end=392
  _globals['_DELETEREPLAYREQUEST']._serialized_start=394
  _globals['_DELETEREPLAYREQUEST']._serialized_end=434
  _globals['_REPLAY']._serialized_start=437
  _globals['_REPLAY']._serialized_end=786
# @@protoc_insertion_point(module_scope)
